In [1]:
## Heros of Pymoli

#### Observed Trend 1
#### Men are 4 times more likely to be playing and purchasing Video games ( Men - 81% Women - 17%)
#### Observed Trend 2
#### As you age you trend to spend more on video games
#### Observed Trend 3
#### Top 5 most popular games are also Highest Grossing games.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_json("purchase_data.json")
df.columns = [ 'Age','Gender','ItemID','ItemName','Price','SN']
df

,Age,Gender,ItemID,ItemName,Price,SN
0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,21,Male,92,Final Critic,1.36,Pheusrical25
4,23,Male,63,Stormfury Mace,1.27,Aela59
5,20,Male,10,Sleepwalker,1.73,Tanimnya91
6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97
7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29
8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63
9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92
10,24,Male,57,"Despair, Favor of Due Diligence",3.81,Chamosia29
11,20,Male,47,"Alpha, Reach of Ending Hope",1.55,Sally64
12,30,Male,81,Dreamkiss,4.06,Iskossa88
13,23,Male,77,"Piety, Guardian of Riddles",3.68,Seorithstilis90
14,40,Male,44,Bonecarvin Battle Axe,2.46,Sundast29
15,21,Male,96,Blood-Forged Skeletal Spine,4.77,Haellysu29
16,22,Female,123,Twilight's Carver,1.14,Sundista85
17,22,Female,59,"Lightning, Etcher of the King",1.65,Aenarap34
18,28,Male,91,Celeste,3.71,Iskista88
19,31,Male,177,"Winterthorn, Defender of Shifting Worlds",4.89,Assossa43
20,24,Male,78,"Glimmer, Ender of the Moon",2.33,Irith83
21,15,Male,3,Phantomlight,1.79,Iaralrgue74
22,11,Female,11,Brimstone,2.52,Deural48
23,19,Male,183,Dragon's Greatsword,2.36,Chanosia65
24,11,Male,65,Conqueror Adamantite Mace,1.96,Qarwen67
25,21,Male,63,Stormfury Mace,1.27,Idai61
26,29,Male,132,Persuasion,3.90,Aerithllora36
27,34,Male,106,Crying Steel Sickle,2.29,Assastnya25
28,15,Male,49,"The Oculus, Token of Lost Worlds",4.23,Ilariarin45
29,16,Female,45,Glinting Glass Edge,2.46,Phaedai25
...,...,...,...,...,...,...
750,23,Male,86,Stormfury Lantern,1.28,Eollym91
751,26,Female,179,"Wolf, Promise of the Moonwalker",1.88,Lisjasksda68
752,15,Female,116,Renewed Skeletal Katana,2.37,Yalostiphos68
753,20,Male,4,Bloodlord's Fetish,2.28,Thryallym62
754,31,Male,104,Gladiator's Glaive,1.36,Sondastan54
755,22,Female,179,"Wolf, Promise of the Moonwalker",1.88,Ailaesuir66
756,22,Male,6,Rusty Skull,1.20,Siasri67
757,35,Male,11,Brimstone,2.52,Seosri62
758,20,Male,122,Unending Tyranny,1.21,Ryastycal90
759,19,Male,87,"Deluge, Edge of the West",2.20,Chanirrasta87
760,29,Male,81,Dreamkiss,4.06,Aerithllora36
761,28,Male,175,Woeful Adamantite Claymore,1.24,Raeduerin33
762,36,Male,52,Hatred,4.39,Lisosiast26
763,27,Other / Non-Disclosed,48,"Rage, Legacy of the Lone Victor",4.32,Eurisuru25
764,25,Male,70,Hope's End,3.89,Assassasda84
765,15,Male,13,Serenity,1.49,Aerithnucal56
766,22,Female,84,Arcane Gem,2.23,Nitherian58
767,20,Male,122,Unending Tyranny,1.21,Hailaphos89
768,21,Male,158,"Darkheart, Butcher of the Champion",3.56,Chamucosda93
769,24,Male,73,Ritual Mace,3.74,Frichilsasya78
770,22,Male,141,Persuasion,3.27,Aenasu69
771,24,Male,25,Hero Cane,1.03,Lassista97
772,15,Male,31,Trickster,2.07,Sidap51
773,21,Male,44,Bonecarvin Battle Axe,2.46,Chamadarsda63
774,24,Male,123,Twilight's Carver,1.14,Lassassast73
775,22,Male,98,"Deadline, Voice Of Subtlety",3.62,Eural50
776,14,Male,104,Gladiator's Glaive,1.36,Lirtossa78
777,20,Male,117,"Heartstriker, Legacy of the Light",4.15,Tillyrin30
778,20,Male,75,Brutality Ivory Warmace,1.72,Quelaton80
779,23,Female,107,"Splitter, Foe Of Subtlety",3.61,Alim85

In [4]:
#Total Number of Players
NumPlayers=df['Age'].count()
print(str(NumPlayers))

780

In [5]:
# Number of Unique Items
df['ItemName'].unique
# Average Purchase Price

<bound method Series.unique of 0                    Bone Crushing Silver Skewer
1      Stormbringer, Dark Blade of Ending Misery
2                                Primitive Blade
3                                   Final Critic
4                                 Stormfury Mace
5                                    Sleepwalker
6                                Mercenary Sabre
7         Interrogator, Blood Blade of the Queen
8               Ghost Reaver, Longsword of Magic
9           Expiration, Warscythe Of Lost Worlds
10               Despair, Favor of Due Diligence
11                   Alpha, Reach of Ending Hope
12                                     Dreamkiss
13                    Piety, Guardian of Riddles
14                         Bonecarvin Battle Axe
15                   Blood-Forged Skeletal Spine
16                             Twilight's Carver
17                 Lightning, Etcher of the King
18                                       Celeste
19      Winterthorn, Defender of Shifting Worlds
20                    Glimmer, Ender of the Moon
21                                  Phantomlight
22                                     Brimstone
23                           Dragon's Greatsword
24                     Conqueror Adamantite Mace
25                                Stormfury Mace
26                                    Persuasion
27                           Crying Steel Sickle
28              The Oculus, Token of Lost Worlds
29                           Glinting Glass Edge
                         ...
750                            Stormfury Lantern
751              Wolf, Promise of the Moonwalker
752                      Renewed Skeletal Katana
753                           Bloodlord's Fetish
754                           Gladiator's Glaive
755              Wolf, Promise of the Moonwalker
756                                  Rusty Skull
757                                    Brimstone
758                             Unending Tyranny
759                     Deluge, Edge of the West
760                                    Dreamkiss
761                   Woeful Adamantite Claymore
762                                       Hatred
763              Rage, Legacy of the Lone Victor
764                                   Hope's End
765                                     Serenity
766                                   Arcane Gem
767                             Unending Tyranny
768           Darkheart, Butcher of the Champion
769                                  Ritual Mace
770                                   Persuasion
771                                    Hero Cane
772                                    Trickster
773                        Bonecarvin Battle Axe
774                            Twilight's Carver
775                  Deadline, Voice Of Subtlety
776                           Gladiator's Glaive
777            Heartstriker, Legacy of the Light
778                      Brutality Ivory Warmace
779                    Splitter, Foe Of Subtlety
Name: ItemName, Length: 780, dtype: object>

In [6]:
# Average Purchase Price
NumPlayers=df['Age'].count()
df['Price'].sum()/NumPlayers

2.931192307692303

In [10]:
# Total Number of Purchases
NumPlayers=df['ItemID'].count()
print("####Player Count")
print(str(NumPlayers))

####Player Count
780

In [8]:
# Total Revenue
df['Price'].sum()

2286.3299999999963

In [9]:

# Percentage and Count of Male Players
#df.loc[df.country == 'US']['id'].count()
#df1['average_backer_us'] = df.loc[df.country == 'US']['id'].count()/df['backers_count'].
male_per=100*df.loc[df.Gender == 'Male']['SN'].count()/NumPlayers
print ( str(round(male_per,2)) )

81.15

In [129]:
# Percentage and Count of Female Players
female_per=100*df.loc[df.Gender == 'Female']['SN'].count()/NumPlayers
print ( str(round(female_per,2)) )

17.44

In [130]:
# Percentage and Count of Other / Non-Disclosed
#surveys_df[(surveys_df.year >= 1980) & (surveys_df.year <= 1985)]
nether_per=100*df.loc[(df.Gender != 'Female') & ( df.Gender != 'Male') ]['SN'].count()/NumPlayers
print ( str(round(nether_per,2)) )

1.41

In [131]:
# The below each broken by gender
  # Purchase Count
pcou = df.loc[df.Gender == 'Male']['SN'].count()
  # Average Purchase Price
pavg =  df.loc[df.Gender == 'Male']['Price'].mean()
  # Total Purchase Value
pval = df.loc[df.Gender == 'Male']['Price'].sum()
  # Normalized Totals
print("Purchase stats by Male---")
print ("Purchase Count:"+str(pcou)+" Avg Price:"+str(round(pavg,2))+" Sum Val:"+str(round(pval,2)) )

Purchase stats by Male---
Purchase Count:633 Avg Price:2.95 Sum Val:1867.68

In [132]:
# The below each broken by gender
  # Purchase Count
pcou = df.loc[df.Gender == 'Female']['SN'].count()
  # Average Purchase Price
pavg =  df.loc[df.Gender == 'Female']['Price'].mean()
  # Total Purchase Value
pval = df.loc[df.Gender == 'Female']['Price'].sum()
  # Normalized Totals
print("Purchase stats by Female---")
print ("Purchase Count:"+str(pcou)+" Avg Price:"+str(round(pavg,2))+" Sum Val:"+str(round(pval,2)) )

Purchase stats by Female---
Purchase Count:136 Avg Price:2.82 Sum Val:382.91

In [133]:
df.loc[ df.SN == 'Undirrala66']

     Age Gender  ItemID                    ItemName  Price           SN
79    29   Male     144      Blood Infused Guardian   2.86  Undirrala66
107   29   Male     115  Spectral Diamond Doomblade   4.25  Undirrala66
131   29   Male      62                 Piece Maker   4.36  Undirrala66
537   29   Male      18  Torchlight, Bond of Storms   1.77  Undirrala66
596   29   Male     133            Faith's Scimitar   3.82  Undirrala66

In [11]:
#**Age Demographics**

#* The below each broken into bins of 4 years (i.e. &lt;10, 10-14, 15-19, etc.) 
#  * Purchase Count
df_10 = df.loc[df.Age < 10]

avg_10 = df_10['Price'].sum()/df_10['Price'].count()
tot_10 = df_10['Price'].sum() 

df_14 = df.loc[ ( df.Age >= 10 ) & (df.Age <= 14) ]

avg_14 = df_14['Price'].sum()/df_14['Price'].count()
tot_14 = df_14['Price'].sum() 

df_19 = df.loc[ ( df.Age <= 15 ) & (df.Age <= 19) ]

avg_19 = df_19['Price'].sum()/df_19['Price'].count()
tot_19 = df_19['Price'].sum() 

#df_19
####Age Demographics**
#### * Average Purchase Price
#### * Total Purchase Value
#### * Normalized Totals
print("Average 10 under:"+str(round(avg_10,2))+" Sum: "+str(round(tot_10,2)) )
print("Average 14 under:"+str(round(avg_14,2))+" Sum: "+str(round(tot_14,2)) )
print("Average 19 under:"+str(round(avg_19,2))+" Sum: "+str(round(tot_19,2)) )

Average 10 under:2.98 Sum: 83.46
Average 14 under:2.77 Sum: 96.95
Average 19 under:2.92 Sum: 320.77

In [161]:
# Identify the the top 5 spenders in the game by total purchase value, then list (in a table):
  # SN  df.groupby('A').sum().sort('B')
  

df1 = df.groupby('SN', sort=False).sum()  
df1['Counts'] = df.groupby(['SN'])['Price'].count()
df1['Average'] = df.groupby(['SN'])['Price'].mean()
df1['Sum'] = df.groupby(['SN'])['Price'].sum()
df1.sort_values(['Price'], ascending=False, inplace=True)
df1.head(5)

             Age  ItemID  Price  Counts   Average    Sum
SN
Undirrala66  145     472  17.06       5  3.412000  17.06
Saedue76     100     233  13.56       4  3.390000  13.56
Mindimnya67  156     609  12.74       4  3.185000  12.74
Haellysu29    63     353  12.73       3  4.243333  12.73
Eoda93        66     284  11.58       3  3.860000  11.58

In [162]:
# Identify the 5 most popular items by purchase count, then list (in a table):
#  * Item ID
#  * Item Name
#  * Purchase Count
#  * Item Price
#  * Total Purchase Value
df2 = df.groupby('ItemName', sort=False).count() 
df2['ItemCount'] = df.groupby(['ItemName'])['Price'].count()
df2.sort_values(['ItemCount'], ascending=False, inplace=True)
df2.head(5)

,Age,Gender,ItemID,Price,SN,ItemCount
ItemName,,,,,,
Final Critic,14,14,14,14,14,14
Arcane Gem,11,11,11,11,11,11
"Betrayal, Whisper of Grieving Widows",11,11,11,11,11,11
Stormcaller,10,10,10,10,10,10
Woeful Adamantite Claymore,9,9,9,9,9,9

In [163]:
df.loc[df.ItemName=='Arcane Gem']

     Age  Gender  ItemID    ItemName  Price             SN
116   25    Male      84  Arcane Gem   2.23     Koikirra25
171   21    Male      84  Arcane Gem   2.23  Stryanastip77
297   24    Male      84  Arcane Gem   2.23     Yarolwen77
338   17    Male      84  Arcane Gem   2.23   Lisossanya98
354   20    Male      84  Arcane Gem   2.23     Mindirra92
416   25    Male      84  Arcane Gem   2.23     Hiarideu73
440   21    Male      84  Arcane Gem   2.23  Stryanastip77
541   20    Male      84  Arcane Gem   2.23   Eosursurap97
711   22    Male      84  Arcane Gem   2.23  Tyananurgue44
742   26    Male      84  Arcane Gem   2.23      Inguron55
766   22  Female      84  Arcane Gem   2.23    Nitherian58

In [164]:
#**Most Profitable Items**
df2 = df.groupby('ItemName', sort=False).count() 
df2.sort_values(['Price'], ascending=False, inplace=True)
df2['ItemValue'] = df.groupby(['ItemName'])['Price'].sum() 
df2.head(5)
# Identify the 5 most profitable items by total purchase value, then list (in a table):
#  * Item ID
#  * Item Name
#  * Purchase Count
#  * Item Price
#  * Total Purchase Value

,Age,Gender,ItemID,Price,SN,ItemValue
ItemName,,,,,,
Final Critic,14,14,14,14,14,38.60
Arcane Gem,11,11,11,11,11,24.53
"Betrayal, Whisper of Grieving Widows",11,11,11,11,11,25.85
Stormcaller,10,10,10,10,10,34.65
Woeful Adamantite Claymore,9,9,9,9,9,11.16